version: "3.9"
services:
  app:
    build:
      context: .
    volumes:
      - .:/japanton-frontend
    ports:
      - 3000:3000
    image: japanton-frontend:japanton
    container_name: JAPANTON
    command: npm start
