export enum RouteNames {
  // eslint-disable-next-line no-unused-vars
  LOGIN = '/login',
  // eslint-disable-next-line no-unused-vars
  SIGNUP = '/signup',
  // eslint-disable-next-line no-unused-vars
  CARS_ACTIVE = '/cars/active',
  // eslint-disable-next-line no-unused-vars
  CARS_CREATE = '/cars/create',
  // eslint-disable-next-line no-unused-vars
  CARS_ITEM = '/cars',
  // eslint-disable-next-line no-unused-vars
  CARS_ARCHIVE = '/cars/archive',
  // eslint-disable-next-line no-unused-vars
  CARS_TYPES_OF_SPARE_PARTS
  = '/cars/types_of_spare_parts',
  // eslint-disable-next-line no-unused-vars
  CARS_SPARE_PARTS = '/cars/spare_parts',
  // eslint-disable-next-line no-unused-vars
  CARS_SPARE_PARTS_STRUCTURE = '/cars/spare_parts_structure',
  // eslint-disable-next-line no-unused-vars
  CARS_CATALOG = '/cars/catalog',
  // eslint-disable-next-line no-unused-vars
  CARS_SUPPLIERS = '/cars/suppliers',
  // eslint-disable-next-line no-unused-vars
  WHEELS1 = '/wheels/test_wheels1',
  // eslint-disable-next-line no-unused-vars
  WHEELS2 = '/wheels/test_wheels2',
  // eslint-disable-next-line no-unused-vars
  WHEELS3 = '/wheels/test_wheels3',
  // eslint-disable-next-line no-unused-vars
  USERS1 = '/users/test_users1',
  // eslint-disable-next-line no-unused-vars
  USERS2 = '/users/test_users2',
  // eslint-disable-next-line no-unused-vars
  USERS3 = '/users/test_users3',
  // eslint-disable-next-line no-unused-vars
  CONTAINERS1 = '/containers/test_containers1',
  // eslint-disable-next-line no-unused-vars
  CONTAINERS2 = '/containers/test_containers2',
  // eslint-disable-next-line no-unused-vars
  CONTAINERS3 = '/containers/test_containers3',
  // eslint-disable-next-line no-unused-vars
  SHIPMENTS1 = '/shipments/test_shipments1',
  // eslint-disable-next-line no-unused-vars
  SHIPMENTS2 = '/shipments/test_shipments2',
  // eslint-disable-next-line no-unused-vars
  SHIPMENTS3 = '/shipments/test_shipments3',
  // eslint-disable-next-line no-unused-vars
  BALANCE1 = '/balance/test_balance1',
  // eslint-disable-next-line no-unused-vars
  BALANCE2 = '/balance/test_balance2',
  // eslint-disable-next-line no-unused-vars
  BALANCE3 = '/balance/test_balance3',
  // eslint-disable-next-line no-unused-vars
  ACCESS1 = '/access/test_access1',
  // eslint-disable-next-line no-unused-vars
  ACCESS2 = '/access/test_access2',
  // eslint-disable-next-line no-unused-vars
  ACCESS3 = '/access/test_access3',
  // eslint-disable-next-line no-unused-vars
  RETAIL1 = '/retail/test_retail1',
  // eslint-disable-next-line no-unused-vars
  RETAIL2 = '/retail/test_retail2',
  // eslint-disable-next-line no-unused-vars
  RETAIL3 = '/retail/test_retail3'
}
